CREATE TABLE STATE
(
    STATE_ID SERIAL,
    NAME     NAME,
    PRIMARY KEY (STATE_ID)
);

CREATE TABLE COLOR
(
    COLOR_ID SERIAL,
    NAME     NAME,
    PRIMARY KEY (COLOR_ID)
);

CREATE TABLE TEAM
(
    TEAM_ID  SERIAL,
    NAME     NAME,
    STATE_ID INT,
    COLOR_ID INT,
    WINS     INT,
    LOSSES   INT,
    PRIMARY KEY (TEAM_ID),
    FOREIGN KEY (STATE_ID) REFERENCES STATE (STATE_ID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (COLOR_ID) REFERENCES COLOR (COLOR_ID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE PLAYER
(
    PLAYER_ID   SERIAL,
    TEAM_ID     INT,
    UNIFORM_NUM INT,
    FIRST_NAME  NAME,
    LAST_NAME   NAME,
    MPG         INT,
    PPG         INT,
    RPG         INT,
    APG         INT,
    SPG         NUMERIC(3, 1),
    BPG         NUMERIC(3, 1),
    PRIMARY KEY (PLAYER_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID) ON DELETE SET NULL ON UPDATE CASCADE
);